name    'ghoneycutt-rpcbind'
version '1.4.0'
source 'git://github.com/ghoneycutt/puppet-module-rpcbind.git'
author 'ghoneycutt'
license 'Apache-2.0'
summary 'Manage rpcbind'
description 'Manages rpcbind'
project_page 'https://github.com/ghoneycutt/puppet-module-rpcbind'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
